database-address: 10.238.222.210
database-username: root
database-password: Iaas@2019
redis-address: 10.238.222.210
redis-password: Pcitc@123!
share:
  host: 10.238.222.210
  port: 8020
  context:

filestorage:
  ip: 10.238.222.210
  host: 10.238.222.210
  port: 8081
  context:

fdfs:
  so-timeout: 1000
  connect-timeout: 500
  tracker-list:
    - 10.238.222.210:22122

wfssourl: http://szgtdps.paas.sinopec.com:8090/dps/sso

pageoffice:
  context: /contract
  opencontext: /contract

maindata:
  url: http://116.253.211.133:33201/dmodel/webservices/CxWsService?wsdl
  modelId: T_2082
  sysCode: INSYS_OUTUNIT
  
secretKey: e2e870169e4811ea93dafa163e120be4
