
package com.pcitc.szgt.contract.offeree.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CxWsService", targetNamespace = "urn:CxWsService")
public interface CxWsService {
    /**
     * 
     * @param sysCode
     * @param modelId
     * @param strtime
     * @param pageNo
     * @param endtime
     * @param pageSize
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RevicesForcxWs")
    @WebResult(name = "response", targetNamespace = "urn:CxWsService")
    @RequestWrapper(localName = "RevicesForcxWs", targetNamespace = "urn:CxWsService", className = "cxwsservice.RevicesForcxWs")
    @ResponseWrapper(localName = "RevicesForcxWsResponse", targetNamespace = "urn:CxWsService", className = "cxwsservice.RevicesForcxWsResponse")
    public String revicesForcxWs(
            @WebParam(name = "modelId", targetNamespace = "urn:CxWsService")
                    String modelId,
            @WebParam(name = "sysCode", targetNamespace = "urn:CxWsService")
                    String sysCode,
            @WebParam(name = "strtime", targetNamespace = "urn:CxWsService")
                    String strtime,
            @WebParam(name = "endtime", targetNamespace = "urn:CxWsService")
                    String endtime,
            @WebParam(name = "pageSize", targetNamespace = "urn:CxWsService")
                    String pageSize,
            @WebParam(name = "pageNo", targetNamespace = "urn:CxWsService")
                    String pageNo);

}
