server:
  port: 8090
  tomcat: 
    max-swallow-size: -1
#  servlet:
#    context-path: /federationWeb
#ferderation
#@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
spring:
  servlet:
    multipart:
      max-file-size: 51200MB
      max-request-size: 51200MB
  profiles:
#    active: szgtprod
    active: szgttest
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #如果使用字符串表示，用这行设置格式(全局配置用于查询时间转化)
    timezone: GMT+8
    serialization:
      write-dates-as-timestamps: false #使用时间戳，使用数值timestamp表示日期
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml #默认配置文件
    #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.pcitc.szgt.entity
  global-config:
    db-config:
      logic-delete-value: 1 #逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 #逻辑未删除值(默认为 0)
      id-type: auto #全局自动增长id
      table-prefix: t_ #表名的前缀
      insert-strategy: not_null #字段插入nuLl字段忽略
      update-strategy: not_null #字段更新nuLl字段忽略
      select-strategy: not_null #where 条件实体类 作为参数 忽略null字段
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
fastdfs:
  tracker-servers: 10.238.222.210:22122
  network-timeout-in-seconds: 30
  connect-timeout-in-seconds: 20

swagger:
  enable: true

dps:
  url: http://10.238.222.210:8020
mdm:
  url: http://116.253.211.133:33201/dmodel/webservices/CxWsService?wsdl
# PageOffice授权文件license.lic所在的目录
pageoffice:
#  posyspath: /Users/lixianming/石化盈科代码/szgt-code-law/springboot-szgt-legal-project/szgt-services/szgt-legalAffairs/src/main/resources/lic/
  posyspath: /home/iaas/szgt-test/service/law/lic
  

