# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER oo

# 挂载目录
VOLUME /home/oo
# 创建目录
RUN mkdir -p /home/oo
# 指定路径
WORKDIR /home/oo
# 复制jar文件到路径
COPY ./jar/oo-modules-system.jar /home/oo/oo-modules-system.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","oo-modules-system.jar"]