#spring:
#  datasource: #数据源
#    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动
#    url: jdbc:mysql://124.70.35.32:3306/gjgs-dc-cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai  # 数据库的 JDBC URL
#    username: root
#    password: yadan2022!@#

#spring:
#  datasource:
#    dynamic:
#      strict: false
#      primary: one
#      datasource: #数据源
#        one:
#          driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动
#          url: jdbc:mysql://124.70.35.32:3306/gjgs-dc?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai  # 数据库的 JDBC URL
#          username: root
#          password: yadan2022!@#


